controllers:
    resource: ../src/Controller/
    type: attribute

api_login_check:
    path: /api/login_check

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /api/logout
    controller: App\Controller\SecurityController::logout

home:
    path: /
    controller: App\Controller\SecurityController::home